---

# - name: Debug teste
#   debug: msg="{{groups.openvpn[0]}}"

- name: Repositorio Epel
  yum_repository:
    name: epel
    description: "Epel"
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
    gpgcheck: yes
    enabled: yes

- name: Instalacao do Openvpn e Easy-rsa
  yum:
    name:
      - easy-rsa
      - openvpn
    state: present


###
### Configuracao de Chaves Criptograficas
- name: Arquivo com as configuracoes do Easy-rsa
  template:
    src: vars
    dest: /etc/openvpn/vars

- name: Verificar se a pasta de chaves já existe
  stat: path=/etc/openvpn/keys/
  register: openvpn_keys

- name: Configuracao Certificados RSA
  shell: |
    test -d /etc/openvpn/keys && exit 0
    source /etc/openvpn/vars
    ./easyrsa init-pki
    ./easyrsa --batch build-ca nopass
    ./easyrsa gen-dh
    ./easyrsa build-server-full server nopass
    openvpn --genkey --secret /etc/openvpn/keys/ta.key
  args:
    chdir: "/usr/share/easy-rsa/3"
  when: openvpn_keys.stat.exists == False


###
### Configuracoes Openvpn
- name: Arquivo com as configuracoes do Openvpn
  template:
    src: server.conf
    dest: /etc/openvpn/server.conf

- name: Arquivo com as configuracoes do Openvpn Client
  template:
    src: client.conf.sample
    dest: /etc/openvpn/client.conf.sample

- name: Servico Openvpn
  service:
    name: openvpn
    state: started
    enabled: yes


###
### Configuracao de script para gerenciamento de usuarios do Openvpn
- name: Criar pastas de Scripts
  file:
    path: /opt/scripts
    state: directory

- name: Script de gerenciamento de usuarios
  template:
    src: vpnuser.sh
    dest: /opt/scripts/vpnuser.sh
    mode: "u=rwx,g=r,o=r"

- file:
    src: /opt/scripts/vpnuser.sh
    dest: /usr/bin/vpnuser
    state: link



- name: Configuracao do nat
  lineinfile:
    path: /etc/rc.local
    line: '/sbin/iptables -t nat -I POSTROUTING -d {{ network }} -j MASQUERADE'

- name: Liberacao de encaminhamento
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: 'net.ipv4.ip_forward = 1'

- name: Aplicar configuracoes de nat e encaminhamento
  shell: |
    /etc/rc.local
    /sbin/sysctl -p


##
## sysctl net.ipv4.ip_forward=1
